### PR TITLE
Split one into two files, merge and minfy those with gulp

### PR DESCRIPTION
**Pull request by k-nut**
As announced I split the one `OverPassLayer.js` into two files that contain the two modules that this library is made of. I also introduced [gulp](http://gulpjs.com/) to combine them.
And while I was at that I also added minification so that we now serve a regular as well as a minified version of the project.
I hope that everything is more or less clear (I put some more information in the readme) and I would be glad to hear your opinion on this and to answer some questions.

### CODE REVIEW

**Comment by kartenkarsten** [comment]
I like the Idea to generate the result - I experimented a bit with grunt but I'm totally okay with gulp as well.
But in my opinion it's not a good Idea to include all necessary node packages. More than 1000 files under version control are definitely too many for such a simple project. I would prefer to remove all dependencies from this repository and let the contributor install them by themselves. Moreover it might be a good idea just to provide an tutorial how to generate the dist files and attach them manually within each new release.

**Comment by k-nut** [comment]
You are right about the load of modules. It used to be best practice to include the `node_modules` folder but [apparently it is not like that anymore](http://stackoverflow.com/questions/11459475/should-i-check-in-node-modules-to-git-when-creating-a-node-js-app-on-heroku).

I prefer it this way as well, seems much cleaner!

Would it be okay for you to just check in the `package.json` and have the user install the dependencies as described in the readme? I think it would be good for the users to be able to check if the combined file works as expected and not just create it on every new release.
I would create a new PR then because if I change this one the files will still be in the git history. Some crazy rebase magic might work around that but I think that I would be better of by just creating a new one with the `node_modules` ignored.
What do you think?

**Comment by kartenkarsten** [comment]
I agree to your plans. We could include ```bower_components``` as well to the ```.gitignore``` file. 

To the content of ```package.json``` it seams author is missing - but I don't know how to handle multiple authors - maybe leaving it blank is the best solution. Moreover I thing all dependencies should be devDependencies. 

I'm waiting for your new PR.

**Comment by k-nut** [comment]
With some help I was able to change this PR so that the unneeded files are not included anymore and do not even appear in the history. Everything should be as discussed.

**Pull request merged**
